#!/bin/sh

cd $SNAP/app/

RAM="$(snapctl get ram)"

ARGS="-Xms256m"

if [ -n "${RAM}" ]; then
  ARGS="${ARGS} -Xmx${RAM}m"
fi

if [ -n "${JVM_ARGS}" ]; then
  ARGS="${JVM_ARGS} ${ARGS}"
fi

set -x

java ${ARGS} -jar ajcore.jar "$@"

