#!/bin/sh

set -e

if [ "$(id -u)" = "0" ]; then
  PUID=${PUID:-1000}
  PGID=${PGID:-1000}

  groupmod -o -g "$PGID" ubuntu
  usermod -o -u "$PUID" ubuntu

  chown ubuntu:ubuntu -R /config/

  if [ ! -f /config/appleJuice/settings.xml ]; then
    mkdir -p /config/appleJuice/
    cp /app/settings.xml /config/appleJuice/settings.xml
    sed -i "s/dockerianer/dockerianer${RANDOM}/" /config/appleJuice/settings.xml
  fi

  exec sudo -Hu ubuntu "$@"
else
  exec "$@"
fi
